# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fcb59850d3174ccdb967c2ffd9eab76cd994ca92e67e41b2aca6c05b8576caa944b95d632ecfefa543732bce49f2851954ee186dea6ea9669dcdb2a23b80a97

test:
  secret_key_base: 670a6243559d5c0fe1783abec107559a6d210d72eab51ec19d1900e6b75917797581bed333bab2ce8c6fd6080b1f2675df01e61a3a5a2461e585ae9847b57784

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
